apiVersion: v1
kind: Pod
metadata:
    name: pod-quota-demo
spec:
    selector:
        matchLabels:
            purpose: pod-quota-demo
    replicas: 3
    template:
        metadata:
            labels:
                purpose: quota-demo
        spec:
            containers:
            - name: pod-quota-demo
              image: nginx